name: Auto Merge Master to Develop

on:
  push:
    branches:
      - master

jobs:
  auto_merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Merge to develop
      run: |
        git checkout master
        git merge develop
        get checkout develop
        git push origin develop
